export const KDA_CONNECT = 'kda_connect'
export const KDA_CHECKSTATUS = 'kda_checkStatus'
export const KDA_GETNETWORK = 'kda_getNetwork'
export const KDA_REQUESTACCOUNT = 'kda_requestAccount'
export const KDA_DISCONNECT = 'kda_disconnect'
export const KDA_REQUESTSIGN = 'kda_requestSign'
